### ISSUE TITLE
How to load an IR file?

### ISSUE THREAD

**Issue by unfa** [x42/convoLV2#3]
I tried loading the plugin in Carla - but it only has Gain parameter, and shows no way of defining the IR file.
![selection_282](https://cloud.githubusercontent.com/assets/491704/23262805/3a14bc9a-f9dc-11e6-8533-487a91ef137d.png)

How can I use this plugin?

**Comment by x42** [comment]
It only works in LV2-Plugin hosts which support the LV2:Patch to set/get filenames, which is pretty common these days, but I don't know about Carla  (Ardour, jalv, qtractor, Mixbus, etc etc support it)

**Comment by falkTX** [comment]
Carla doesn't support this yet, but I'll add it eventually.
