### ISSUE TITLE
Please do a release of x42-plugins.

### ISSUE THREAD

**Issue by magnetophon** [x42/convoLV2#6]
Since that repo doesn't have issues enabled, and since this plugin doesn\t build for me, I'm asking here:

Could you do a release that includes compatibility with ``zita-convolver-4.0.0``?

Thanks!

**Comment by x42** [comment]
It's already on my list, pending some development of dpl.lv2 and probably won't happen before end or July.

Keep in mind that if you don't statically link the plugins, all plugins must use the exact same version of libzita-convolver (e.g. guitarix, IR.lv2 and others need to be updated in lock-step)

**Comment by magnetophon** [comment]
@x42 Thanks.
I'll wait.

**Comment by dvzrv** [comment]
I'd also be happy with a new release, so I can pull zita-convolver up to 4.0.0 for Arch.
However, other projects are also still adapting the changes ;-)
Thanks!

**Comment by x42** [comment]
Done: https://gareus.org/misc/x42-plugins/x42-plugins-20180803.tar.xz
https://gareus.org/misc/x42-plugins/x42-plugins-20180803.tar.xz.sha1sum (3d6fe0c1bf584d9f62a06a7a359898b172fd6858)

**Comment by magnetophon** [comment]
Thanks!
